baseURL = "//nrriquelmeg.cl/"
# baseURL = "http://localhost:80/PersonalPage/"
languageCode = "en-us"
title = "Nicolás Rafael Riquelme Guzmán"
publicdir = "public"

[params]
    profesion = "Historiador / Desarrollador Web / Ciclista"
    about = "Programador wanabe oriundo de Santiago de Chile."
    like = "Me apasiona aprender, comprender e integrar nuevos conocimientos."
